/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_user_files_s3_bucket": "devi-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6951a3f0-2e36-4f4b-afdc-53ba92430fcf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cQCWLp8CV",
    "aws_user_pools_web_client_id": "4arvmjnkb1gj6lnq08ddq9es78",
    "oauth": {},
};

// const awsmobile = {
//     "aws_user_files_s3_bucket": "deviai",
//     "aws_user_files_s3_bucket_region": "us-east-2",
//     "aws_project_region": "us-east-2",
//     "aws_cognito_identity_pool_id": "us-east-2:dec85ec5-580b-4860-a563-c914f1e1d9df",
//     "aws_cognito_region": "us-east-2",
//     "aws_user_pools_id": "us-east-2_Qws70dwlL",
//     "aws_user_pools_web_client_id": "3758n19er2f8f6spf73r8oihti",
//     "oauth": {},
// };

export default awsmobile;
